### ISSUE TITLE
Does not work if used as the first statement

### ISSUE THREAD

**Issue by xeptore** [herrmanno/babel-plugin-conditional-compilation#1]
Hi!
With `DEBUG` key set to `false`, why does this:
```js
console.log('HERE');
"#if DEBUG";
const sum = require('./sum');
console.log(sum(1, 2));
"#else"
console.log('0')
"#endif";
```
outputs this:
```js
console.log('HERE');
console.log('0');
```
but this:
```js
"#if DEBUG";
const sum = require('./sum');
console.log(sum(1, 2));
"#else"
console.log('0')
"#endif";
```
generates this:
```js
"#if DEBUG";

const sum = require('./sum');

console.log(sum(1, 2));
console.log('0');
```

It seems if it gets used as the first statement, it gets ignored. Am I doing something wrong?

**Comment by herrmanno** [comment]
This seems to be a bug within the babel parser. Using [Babylon](https://www.npmjs.com/package/babylon), the parser used by the babel version in regard, it seems to produce an AST ignoring the first string literal (`"#if DEBUG"`). Therefore, the plugin is unable to process it.

![SCR-20220718-fa6](https://user-images.githubusercontent.com/3965334/179480362-0485f11b-0186-4bcf-a2c5-554574918d55.png)


I've also testet the behaviour against current babel verions (`"@babel/core": "7.18.6"`), but it fails in a similar way.

Sorry I can't help you in any way with this. I'm closing the Issue for now, because as a plugin author, I cannot fix a problem that is out of scope of what a plugin is (currently) able to do inside the babel ecosystem.

Please feel free to open a PR with successful tests, if you find another way to achieve the desired behaviour.
